// Code generated by protoc-gen-go. DO NOT EDIT.
// source: course.proto

package course

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type CourseResponse struct {
	Status               int32             `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Values               map[string]string `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CourseResponse) Reset()         { *m = CourseResponse{} }
func (m *CourseResponse) String() string { return proto.CompactTextString(m) }
func (*CourseResponse) ProtoMessage()    {}
func (*CourseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad75674299e1bb1e, []int{0}
}

func (m *CourseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseResponse.Unmarshal(m, b)
}
func (m *CourseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseResponse.Marshal(b, m, deterministic)
}
func (m *CourseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseResponse.Merge(m, src)
}
func (m *CourseResponse) XXX_Size() int {
	return xxx_messageInfo_CourseResponse.Size(m)
}
func (m *CourseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CourseResponse proto.InternalMessageInfo

func (m *CourseResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CourseResponse) GetValues() map[string]string {
	if m != nil {
		return m.Values
	}
	return nil
}

// The response message containing the greetings
type CourseRequest struct {
	Type                 int32             `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Router               string            `protobuf:"bytes,2,opt,name=router,proto3" json:"router,omitempty"`
	Parameters           map[string]string `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CourseRequest) Reset()         { *m = CourseRequest{} }
func (m *CourseRequest) String() string { return proto.CompactTextString(m) }
func (*CourseRequest) ProtoMessage()    {}
func (*CourseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad75674299e1bb1e, []int{1}
}

func (m *CourseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseRequest.Unmarshal(m, b)
}
func (m *CourseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseRequest.Marshal(b, m, deterministic)
}
func (m *CourseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseRequest.Merge(m, src)
}
func (m *CourseRequest) XXX_Size() int {
	return xxx_messageInfo_CourseRequest.Size(m)
}
func (m *CourseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CourseRequest proto.InternalMessageInfo

func (m *CourseRequest) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *CourseRequest) GetRouter() string {
	if m != nil {
		return m.Router
	}
	return ""
}

func (m *CourseRequest) GetParameters() map[string]string {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func init() {
	proto.RegisterType((*CourseResponse)(nil), "course.CourseResponse")
	proto.RegisterMapType((map[string]string)(nil), "course.CourseResponse.ValuesEntry")
	proto.RegisterType((*CourseRequest)(nil), "course.CourseRequest")
	proto.RegisterMapType((map[string]string)(nil), "course.CourseRequest.ParametersEntry")
}

func init() { proto.RegisterFile("course.proto", fileDescriptor_ad75674299e1bb1e) }

var fileDescriptor_ad75674299e1bb1e = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0xd9, 0xc6, 0x06, 0x9c, 0xf8, 0xc5, 0xa0, 0x35, 0xe4, 0x54, 0x02, 0x42, 0x4f, 0x39,
	0x54, 0x0f, 0x5a, 0xf0, 0x52, 0x09, 0x5e, 0x43, 0x04, 0xef, 0xb1, 0xcc, 0x41, 0xd4, 0x6e, 0xdc,
	0x9d, 0x2d, 0xe4, 0x69, 0x7c, 0x16, 0xdf, 0x4c, 0x32, 0xbb, 0x91, 0x5a, 0x7a, 0xf1, 0x36, 0xff,
	0xf9, 0xf8, 0xef, 0x6f, 0x76, 0xe0, 0x68, 0xa5, 0x9d, 0xb1, 0x54, 0xb4, 0x46, 0xb3, 0xc6, 0xd8,
	0xab, 0xfc, 0x4b, 0xc1, 0xc9, 0x83, 0x84, 0x35, 0xd9, 0x56, 0xaf, 0x2d, 0xe1, 0x04, 0x62, 0xcb,
	0x0d, 0x3b, 0x9b, 0xaa, 0xa9, 0x9a, 0x8d, 0xeb, 0xa0, 0x70, 0x01, 0xf1, 0xa6, 0x79, 0x77, 0x64,
	0xd3, 0x68, 0x1a, 0xcd, 0x92, 0x79, 0x5e, 0x04, 0xc7, 0xbf, 0xf3, 0xc5, 0xb3, 0x34, 0x95, 0x6b,
	0x36, 0x5d, 0x1d, 0x26, 0xb2, 0x3b, 0x48, 0xb6, 0xd2, 0x78, 0x06, 0xd1, 0x1b, 0x75, 0xe2, 0x7f,
	0x58, 0xf7, 0x21, 0x9e, 0xc3, 0x58, 0x5a, 0xd3, 0x91, 0xe4, 0xbc, 0x58, 0x8c, 0x6e, 0x55, 0xfe,
	0xad, 0xe0, 0x78, 0x78, 0xe1, 0xd3, 0x91, 0x65, 0x44, 0x38, 0xe0, 0xae, 0xa5, 0x80, 0x27, 0x71,
	0x0f, 0x6d, 0xb4, 0x63, 0x32, 0xc1, 0x20, 0x28, 0x2c, 0x01, 0xda, 0xc6, 0x34, 0x1f, 0xc4, 0x64,
	0x06, 0xf0, 0xab, 0x5d, 0x70, 0xb1, 0x2d, 0xaa, 0xdf, 0x3e, 0xcf, 0xbe, 0x35, 0x98, 0xdd, 0xc3,
	0xe9, 0x4e, 0xf9, 0x3f, 0x3b, 0xcc, 0xcb, 0x61, 0x85, 0x27, 0x32, 0x9b, 0xd7, 0x15, 0xe1, 0x0d,
	0x44, 0x8f, 0xc4, 0x78, 0xb1, 0x97, 0x24, 0x9b, 0xec, 0xff, 0xd9, 0xe5, 0x25, 0x84, 0xb3, 0x2d,
	0x13, 0x5f, 0xa9, 0xfa, 0x5b, 0x56, 0xea, 0x25, 0x96, 0xa3, 0x5e, 0xff, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xea, 0x46, 0x7b, 0x75, 0xe4, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CourseServiceClient is the client API for CourseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CourseServiceClient interface {
	// 单一请求应答，一对一
	Get(ctx context.Context, in *CourseRequest, opts ...grpc.CallOption) (*CourseResponse, error)
}

type courseServiceClient struct {
	cc *grpc.ClientConn
}

func NewCourseServiceClient(cc *grpc.ClientConn) CourseServiceClient {
	return &courseServiceClient{cc}
}

func (c *courseServiceClient) Get(ctx context.Context, in *CourseRequest, opts ...grpc.CallOption) (*CourseResponse, error) {
	out := new(CourseResponse)
	err := c.cc.Invoke(ctx, "/course.CourseService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CourseServiceServer is the server API for CourseService service.
type CourseServiceServer interface {
	// 单一请求应答，一对一
	Get(context.Context, *CourseRequest) (*CourseResponse, error)
}

func RegisterCourseServiceServer(s *grpc.Server, srv CourseServiceServer) {
	s.RegisterService(&_CourseService_serviceDesc, srv)
}

func _CourseService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/course.CourseService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).Get(ctx, req.(*CourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CourseService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "course.CourseService",
	HandlerType: (*CourseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _CourseService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "course.proto",
}
